// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbnvc0hRVETBwVShOPahUYuLLqMhx79mk',
    appId: '1:471313724069:web:1599a7e808a15ce49fd34c',
    messagingSenderId: '471313724069',
    projectId: 'flutter-firebase-tut-9329d',
    authDomain: 'flutter-firebase-tut-9329d.firebaseapp.com',
    storageBucket: 'flutter-firebase-tut-9329d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbEku73UTZt_qfc4KuOxNcJp9Ry8QVtyo',
    appId: '1:471313724069:android:0a25acbf76f7d1b59fd34c',
    messagingSenderId: '471313724069',
    projectId: 'flutter-firebase-tut-9329d',
    storageBucket: 'flutter-firebase-tut-9329d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi35UgT266M7FmBfLzDIP38GVCcKdN7Gg',
    appId: '1:471313724069:ios:e875513552b1d1899fd34c',
    messagingSenderId: '471313724069',
    projectId: 'flutter-firebase-tut-9329d',
    storageBucket: 'flutter-firebase-tut-9329d.firebasestorage.app',
    iosBundleId: 'com.example.myPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi35UgT266M7FmBfLzDIP38GVCcKdN7Gg',
    appId: '1:471313724069:ios:e875513552b1d1899fd34c',
    messagingSenderId: '471313724069',
    projectId: 'flutter-firebase-tut-9329d',
    storageBucket: 'flutter-firebase-tut-9329d.firebasestorage.app',
    iosBundleId: 'com.example.myPortfolio',
  );
}
